### ISSUE TITLE
API proposal

### ISSUE THREAD

**Issue by stoeffel** [fp-js/fj-cond#1]
checkout https://gist.github.com/stoeffel/39d608e4a626c65a1329

@hemanth which API do you like most?

**Comment by hemanth** [comment]
I would vote for the second one.

**Comment by stoeffel** [comment]
I actually like the first one.
It doesn't use optional arguments.
and you can do this:

``` js
function getConditions() {
  // return array with conditions
}
cond(getConditions());
```

**Comment by hemanth** [comment]
Second one was much like `ramda` :)

**Comment by stoeffel** [comment]
Yes, I know :smile_cat:
The first one is more FP-like in my opinion.

**Comment by hemanth** [comment]
OK then :) 

BTW  `fj-ifElse` syntax is OK ?

**Comment by stoeffel** [comment]
done

**Comment by hemanth** [comment]
:+1:
